[project]
name = "address-analyzing-tool"
version = "1.0.0"
description = "A tool for analyzing URLs, web addresses, IPs for malicious behavior"
dependencies = [
  "flask",
  "vt-py",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
